# Generated by Django 5.0.2 on 2025-10-12 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0004_exercise_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20)),
                ('goal', models.CharField(choices=[('weight_loss', 'Похудение'), ('muscle_gain', 'Набор массы'), ('endurance', 'Выносливость'), ('maintenance', 'Поддержание формы')], default='maintenance', max_length=20)),
                ('training_type', models.CharField(choices=[('home', 'Дом'), ('gym', 'Зал')], default='home', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
            ],
            options={
                'unique_together': {('program', 'exercise')},
            },
        ),
        migrations.AddField(
            model_name='program',
            name='exercises',
            field=models.ManyToManyField(related_name='programs', through='programs.ProgramExercise', to='exercises.exercise'),
        ),
    ]
