# Generated by Django 5.0.2 on 2025-10-07 15:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20)),
                ('goal', models.CharField(choices=[('weight_loss', 'Похудение'), ('muscle_gain', 'Набор массы'), ('endurance', 'Выносливость'), ('maintenance', 'Поддержание формы')], default='maintenance', max_length=20)),
                ('training_type', models.CharField(choices=[('home', 'Дом'), ('gym', 'Зал')], default='home', max_length=10)),
                ('exercises', models.ManyToManyField(related_name='programs', to='exercises.exercise')),
            ],
        ),
    ]
