# Generated by Django 5.0.2 on 2025-10-12 11:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_video'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='exercises',
        ),
        migrations.CreateModel(
            name='ProgramWorkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_workouts', to='programs.program')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('program', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ProgramWorkoutExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='programs.programworkout')),
            ],
            options={
                'unique_together': {('workout', 'exercise')},
            },
        ),
        migrations.DeleteModel(
            name='ProgramExercise',
        ),
    ]
