# Generated by Django 5.0.2 on 2025-10-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_remove_program_exercises_programworkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='frequency',
            field=models.CharField(blank=True, help_text="Например: '3 раза в неделю' или '2x2'", max_length=20),
        ),
    ]
