# Generated by Django 5.0.2 on 2025-10-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_program_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='training_type',
            field=models.CharField(choices=[('home', 'Дома'), ('gym', 'В зале')], default='home', max_length=10),
        ),
    ]
