# Generated by Django 5.0.2 on 2025-10-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_program_level_alter_program_training_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/'),
        ),
    ]
