# Generated by Django 5.0.2 on 2025-10-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_program_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='temp/programs/'),
        ),
    ]
