# Generated by Django 5.0.2 on 2025-10-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_program_image_url_alter_program_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='image',
        ),
    ]
