# Generated by Django 5.0.2 on 2025-10-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_remove_program_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programworkoutexercise',
            name='reps',
        ),
        migrations.AddField(
            model_name='programworkoutexercise',
            name='reps_max',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programworkoutexercise',
            name='reps_min',
            field=models.PositiveIntegerField(default=8),
            preserve_default=False,
        ),
    ]
