# Generated by Django 5.0.2 on 2025-10-13 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_program_level_alter_program_training_type'),
        ('workouts', '0002_alter_workout_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_workouts', to='programs.program'),
        ),
    ]
