# Generated by Django 5.0.2 on 2025-10-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_workout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='custom_exercise',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
