# Generated by Django 5.0.2 on 2025-10-13 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_video'),
        ('workouts', '0005_workoutexercise_custom_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='custom_exercise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise'),
        ),
    ]
