# Generated by Django 5.0.2 on 2025-10-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_alter_workoutexercise_custom_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='custom_exercise',
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
