# Generated by Django 5.0.2 on 2025-10-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_program_level_alter_program_training_type'),
        ('workouts', '0007_remove_workoutexercise_custom_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='program_workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='programs.programworkout'),
        ),
    ]
