# Generated by Django 5.0.2 on 2025-10-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_workout_program_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
