# Generated by Django 5.0.2 on 2025-10-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Рост в сантиметрах', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, help_text='Вес в килограммах', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='training_type',
            field=models.CharField(choices=[('home', 'Дома'), ('gym', 'В зале')], default='home', max_length=10),
        ),
    ]
