# Generated by Django 5.0.2 on 2025-10-13 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_program_level_alter_program_training_type'),
        ('users', '0002_user_height_user_weight_alter_user_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_program',
            field=models.ForeignKey(blank=True, help_text='Выбранная пользователем программа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_selected', to='programs.program'),
        ),
    ]
