# Generated by Django 5.0.2 on 2025-10-07 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('muscle_group', models.CharField(choices=[('chest', 'Грудь'), ('back', 'Спина'), ('legs', 'Ноги'), ('arms', 'Руки'), ('shoulders', 'Плечи'), ('core', 'Пресс')], max_length=20)),
                ('equipment_needed', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/')),
            ],
        ),
    ]
