# Generated by Django 5.0.2 on 2025-10-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='technique',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
