# Generated by Django 5.0.2 on 2025-10-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Начальный'), ('medium', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20),
        ),
    ]
