# Generated by Django 5.0.2 on 2025-10-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='exercises/videos/'),
        ),
    ]
