# Generated by Django 5.0.2 on 2025-10-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_exercise_image_url_exercise_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='image',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='video',
        ),
    ]
